export const data = {
  name: "Mohd Maroof",
  position: "Senior Frontend Developer",
  location: "India",
  country: "India",
  summary:
    "Senior Frontend Developer with 6+ years of experience building scalable web and mobile applications using React, Next.js, and React Native. Proven track record in delivering production-ready MVPs, improving performance, and implementing real-time product experiences with clean architecture and user-focused design.",
  work: [
    {
      organisation: "Ethos",
      role: "Senior Frontend Developer (Contract)",
      from: "February 2026",
      to: "Present",
      location: "Remote",
      labels: [
        "Building Ascend, a React Native mobile application for sales operations.",
        "Developed a custom QR code scanner to streamline product and client workflows.",
        "Designed and implemented end-to-end UX flows to improve field usability and execution speed.",
      ],
    },
    {
      organisation: "VAHN",
      role: "Senior Frontend Developer",
      from: "December 2024",
      to: "January 2026",
      location: "Hyderabad",
      labels: [
        "Built Fleet App MVP and delivered the first production release.",
        "Improved application maintainability and performance using TypeScript and Zustand.",
        "Integrated Mixpanel analytics to track user behavior and support product decisions.",
      ],
    },
    {
      organisation: "Mercor",
      role: "Senior Frontend Developer",
      from: "April 2024",
      to: "November 2024",
      location: "Remote",
      labels: [
        "Developed reusable components for the Lystface project.",
        "Built responsive dashboard interfaces and an official marketing website.",
      ],
    },
    {
      organisation: "Buzztales Technologies Pvt. Ltd.",
      role: "Founder",
      from: "November 2023",
      to: "November 2024",
      location: "India",
      labels: [
        "Founded and led a technology startup delivering digital solutions.",
        "Architected scalable systems and managed end-to-end product lifecycle delivery.",
      ],
    },
    {
      organisation: "56 Secure",
      role: "Frontend Developer",
      from: "March 2021",
      to: "October 2023",
      location: "Remote",
      labels: [
        "Built Admin, Guard, and Police dashboards from scratch.",
        "Integrated Google Maps API for real-time live tracking workflows.",
        "Developed Smart Eye alert features for monitoring and response coordination.",
      ],
    },
    {
      organisation: "Noon Academy",
      role: "Frontend Developer",
      from: "November 2019",
      to: "February 2021",
      location: "Bangalore",
      labels: [
        "Integrated RTC and RTM capabilities using PubNub.",
        "Built breakout room workflows with auto-reconnect logic for reliability.",
        "Set up Storybook to enable component-driven development and UI consistency.",
      ],
    },
  ],

  skills: [
    "React",
    "Next.js",
    "React Native",
    "JavaScript",
    "TypeScript",
    "Zustand",
    "Redux",
    "MobX",
    "Node.js",
    "MongoDB",
    "Mixpanel",
    "Storybook",
    "PubNub",
    "Google Maps API",
    "Performance Optimization",
    "Real-time Systems",
    "Dashboard Development",
    "Reusable Component Architecture",
  ],
};