export const data = {
  name: "Mohd Maroof",
  position: "Senior Frontend Developer",
  location: "India",
  country: "India",
  summary:
    "Senior Frontend Developer with 6+ years of experience building scalable web and mobile applications using React, Next.js, and React Native. Proven track record in delivering production-ready MVPs, improving performance, and implementing real-time product experiences with clean architecture and user-focused design.",
  social: {
    github: "https://github.com/mdmaroof",
    linkedin: "https://linkedin.com/in/mohd-maroof-535619118",
    email: "maroofmohdmalik@gmail.com",
  },
  subtitles: [
    "Senior Frontend Developer",
    "React & Next.js Specialist",
    "Mobile App Builder",
    "UI Architecture Expert",
  ],
  work: [
    {
      organisation: "Ethos",
      role: "Senior Frontend Developer (Contract)",
      from: "February 2026",
      to: "Present",
      location: "Remote",
      labels: [
        "Building Ascend, a React Native mobile application for sales operations.",
        "Developed a custom QR code scanner to streamline product and client workflows.",
        "Designed and implemented end-to-end UX flows to improve field usability and execution speed.",
      ],
    },
    {
      organisation: "VAHN",
      role: "Senior Frontend Developer",
      from: "December 2024",
      to: "January 2026",
      location: "Hyderabad",
      labels: [
        "Built Fleet App MVP and delivered the first production release.",
        "Improved application maintainability and performance using TypeScript and Zustand.",
        "Integrated Mixpanel analytics to track user behavior and support product decisions.",
      ],
    },
    {
      organisation: "Mercor",
      role: "Senior Frontend Developer",
      from: "April 2024",
      to: "November 2024",
      location: "Remote",
      labels: [
        "Developed reusable components for the Lystface project.",
        "Built responsive dashboard interfaces and an official marketing website.",
      ],
    },
    {
      organisation: "Buzztales Technologies Pvt. Ltd.",
      role: "Founder",
      from: "November 2023",
      to: "November 2024",
      location: "India",
      labels: [
        "Founded and led a technology startup delivering digital solutions.",
        "Architected scalable systems and managed end-to-end product lifecycle delivery.",
      ],
    },
    {
      organisation: "56 Secure",
      role: "Frontend Developer",
      from: "March 2021",
      to: "October 2023",
      location: "Remote",
      labels: [
        "Built Admin, Guard, and Police dashboards from scratch.",
        "Integrated Google Maps API for real-time live tracking workflows.",
        "Developed Smart Eye alert features for monitoring and response coordination.",
      ],
    },
    {
      organisation: "Noon Academy",
      role: "Frontend Developer",
      from: "November 2019",
      to: "February 2021",
      location: "Bangalore",
      labels: [
        "Integrated RTC and RTM capabilities using PubNub.",
        "Built breakout room workflows with auto-reconnect logic for reliability.",
        "Set up Storybook to enable component-driven development and UI consistency.",
      ],
    },
  ],

  skills: [
    "React",
    "Next.js",
    "React Native",
    "JavaScript",
    "TypeScript",
    "Zustand",
    "Redux",
    "MobX",
    "Node.js",
    "MongoDB",
    "Mixpanel",
    "Storybook",
    "PubNub",
    "Google Maps API",
    "Performance Optimization",
    "Real-time Systems",
    "Dashboard Development",
    "Reusable Component Architecture",
  ],
  projects: [
    {
      name: "Graple.ai",
      icon: "📊",
      tagline: "Boost engagement with data-driven experiments",
      description:
        "A full-stack experimentation and retention platform that helps product teams design, launch, and analyze A/B tests and engagement campaigns. Built with a real-time analytics dashboard for tracking user behavior and conversion metrics.",
      tech: ["React", "Next.js", "Node.js", "MongoDB", "TypeScript"],
      features: [
        "Real-time A/B testing dashboard",
        "User cohort segmentation engine",
        "Retention funnel visualization",
        "Campaign builder with drag-and-drop",
      ],
      gradient: "from-violet-600 to-indigo-600",
      gradientBorder: "from-violet-500/50 to-indigo-500/50",
      status: "Live",
      link: "https://graple.ai",
    },
    {
      name: "SnapAid",
      icon: "🏥",
      tagline: "Instant medical guidance when seconds count",
      description:
        "An emergency medical guidance web application that provides step-by-step first-aid instructions using AI-powered symptom analysis. Designed for accessibility and speed in critical situations with offline-first capabilities.",
      tech: ["React", "TypeScript", "Node.js", "AI/ML APIs"],
      features: [
        "AI-powered symptom triage",
        "Step-by-step emergency protocols",
        "Offline-first Progressive Web App",
        "Location-based hospital finder",
      ],
      gradient: "from-emerald-600 to-cyan-600",
      gradientBorder: "from-emerald-500/50 to-cyan-500/50",
      status: "Live",
      link: null,
    },
    {
      name: "Twist N Words",
      icon: "🎮",
      tagline: "Challenge your vocabulary with word puzzles",
      description:
        "An interactive word shuffle game that challenges players to unscramble letters and form words against the clock. Features progressive difficulty, streak tracking, and a clean, responsive interface built for both mobile and desktop.",
      tech: ["React", "JavaScript", "CSS Animations", "Local Storage"],
      features: [
        "Progressive difficulty levels",
        "Streak & high score tracking",
        "Smooth drag-and-drop letters",
        "Mobile-optimized touch controls",
      ],
      gradient: "from-amber-500 to-orange-600",
      gradientBorder: "from-amber-500/50 to-orange-500/50",
      status: "Live",
      link: null,
    },
  ],
};